name: Build and Deploy

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_ENVIRONMENT: ${{ inputs.environment }}

    steps:
      - name: Testing
        run: |
          echo Environment ${{ inputs.environment }}
          env

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: groupdocs-cloud/products.groupdocs.cloud
          ref: convert
          token: ${{ secrets.PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          extended: true

      - name: Install Node.js Dependencies
        run: npm install

      - name: Process markdown
        run: npm run generate

      - name: Build
        run: hugo --config=config-stage.toml
